// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsDev {
  static FirebaseOptions get currentPlatformDev {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-3OEpqJQ6rUPITOntt8x3KnS8B7xFEGg',
    appId: '1:802915754045:android:297d50917fcff94fd08a54',
    messagingSenderId: '802915754045',
    projectId: 'viva-fm-smart-ced7c',
    storageBucket: 'viva-fm-smart-ced7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKDQBpxui_Ga0cUkMcfXRG5Rfn6IuqGew',
    appId: '1:802915754045:ios:60c1cc5b86931d62d08a54',
    messagingSenderId: '802915754045',
    projectId: 'viva-fm-smart-ced7c',
    storageBucket: 'viva-fm-smart-ced7c.appspot.com',
    androidClientId:
        '802915754045-55jg2sa27psmg0pn5m0mvb7omins5kb7.apps.googleusercontent.com',
    iosClientId:
        '802915754045-gapjrrfe1h690ki1jagrpu6dpikr6e67.apps.googleusercontent.com',
    iosBundleId: 'com.crdappsperu.viva-fm-smart',
  );
}
